steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/cicd-project=383510/r/cicd=gke']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:$SHORT_SHA']
