steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/sanjayviru/gkecicd.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}', '.']
  env:
    - 'PROJECT_ID=friendly-folio-408616'
    - 'IMAGE_NAME=cicd-image'
    - 'SHORT_SHA=v1.0'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${SHORT_SHA}']
  env:
    - 'PROJECT_ID=friendly-folio-408616'
    - 'IMAGE_NAME=cicd-image'
    - 'SHORT_SHA=v1.0'
